# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/arbiter_gui.ui'
#
# Created: Sat Apr 11 21:56:40 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(695, 620)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs_main = QtGui.QTabWidget(self.centralwidget)
        self.tabs_main.setMinimumSize(QtCore.QSize(0, 0))
        self.tabs_main.setObjectName("tabs_main")
        self.tab_data = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_data.sizePolicy().hasHeightForWidth())
        self.tab_data.setSizePolicy(sizePolicy)
        self.tab_data.setObjectName("tab_data")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_data)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_import = QtGui.QPushButton(self.tab_data)
        self.button_import.setObjectName("button_import")
        self.horizontalLayout.addWidget(self.button_import)
        self.button_remove = QtGui.QPushButton(self.tab_data)
        self.button_remove.setObjectName("button_remove")
        self.horizontalLayout.addWidget(self.button_remove)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabs_data = QtGui.QTabWidget(self.tab_data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs_data.sizePolicy().hasHeightForWidth())
        self.tabs_data.setSizePolicy(sizePolicy)
        self.tabs_data.setMinimumSize(QtCore.QSize(0, 200))
        self.tabs_data.setObjectName("tabs_data")
        self.tab_data_template = QtGui.QWidget()
        self.tab_data_template.setObjectName("tab_data_template")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_data_template)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = DataTableWidget(self.tab_data_template)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.tabs_data.addTab(self.tab_data_template, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabs_data.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabs_data)
        self.frame = QtGui.QFrame(self.tab_data)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.plot_data = MatplotlibWidget(self.frame)
        self.plot_data.setGeometry(QtCore.QRect(9, 9, 631, 291))
        self.plot_data.setObjectName("plot_data")
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabs_main.addTab(self.tab_data, "")
        self.tab_model = QtGui.QWidget()
        self.tab_model.setObjectName("tab_model")
        self.tabs_main.addTab(self.tab_model, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.tabs_main.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabs_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs_main.setCurrentIndex(0)
        self.tabs_data.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Arbiter", None, QtGui.QApplication.UnicodeUTF8))
        self.button_import.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.button_remove.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_data.setTabText(self.tabs_data.indexOf(self.tab_data_template), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_data.setTabText(self.tabs_data.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab_data), QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab_model), QtGui.QApplication.translate("MainWindow", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Fit", None, QtGui.QApplication.UnicodeUTF8))

from custom_widgets import MatplotlibWidget, DataTableWidget
